[2024-04-08 22:27:11,293: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-08 22:27:11,293: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-08 22:27:11,293: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-08 22:27:11,293: INFO: common: created directory at: artifacts]
[2024-04-08 22:27:11,293: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-08 22:27:11,293: INFO: data_ingestion: File already exists of size: ~ 7718 KB]
[2024-04-08 22:27:11,433: INFO: data_ingestion: Extraction Compelete]
[2024-04-08 22:27:11,449: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-04-08 22:27:11,449: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-04-08 22:27:11,449: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-08 22:27:11,449: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-08 22:27:11,449: INFO: common: created directory at: artifacts]
[2024-04-08 22:27:11,455: INFO: common: created directory at: artifacts/data_validation]
[2024-04-08 22:27:11,455: ERROR: main: name 'DataValidation' is not defined]
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    data_validation.main()
  File "c:\users\hites\onedrive\desktop\end to end ml project\text-summarization-nlp-project\src\textSummarizer\pipeline\data_validation.py", line 11, in main
    data_validation_config = config.get_data_validation_config()
  File "c:\users\hites\onedrive\desktop\end to end ml project\text-summarization-nlp-project\src\textSummarizer\config\configuration.py", line 36, in get_data_validation_config
    data_validation_config = DataValidation(
NameError: name 'DataValidation' is not defined
